id: PEE49445C
initial_creation_type: ocr
source_metadata:
  volumes:
    b9db3c3705324761bb59462d78d3ef63:
      base_file: v052.txt
      image_group_id: I1PD95897
      title: མངོན་པར་རྟོགས་པའི་རྒྱན་ཞེས་བྱ་བའི་འགྲེལ་པ་རྟོགས་པར་དཀའ་བའི་སྣང་བ་ཞེས་བྱ་བའི་འགྲེལ་བཤད།
      total_pages: 1426
      volume_number: 52
