id: PEE49445C
initial_creation_type: ocr
source_metadata:
  volumes:
    f156d4098bc64676b746b8c0ed5ce49b:
      base_file: v052.txt
      image_group_id: I1PD95897
      title: མངོན་པར་རྟོགས་པའི་རྒྱན་ཞེས་བྱ་བའི་འགྲེལ་པ་རྟོགས་པར་དཀའ་བའི་སྣང་བ་ཞེས་བྱ་བའི་འགྲེལ་བཤད།
      total_pages: 1426
      volume_number: 52
